apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: echo-service 
    spec:
      containers:
        - name: echo-service
          image: your-host.azurecr.io/echo-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 4Gi
          volumeMounts:
            - name: configmap-volume
              mountPath: /etc/config
      imagePullSecrets:
        - name: acr-auth
      volumes:
        - name: configmap-volume
          configMap:
            name: "special-config"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-service-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 40
